"""
Tren Rezervasyon Sistemi - Başlangıç Scripti
Bu script projenin genel bilgilerini gösterir ve kurulum adımlarını listeler.
"""

print("=" * 80)
print(" " * 20 + "🚂 TREN REZERVASYOn SİSTEMİ 🚂")
print("=" * 80)
print()
print("📋 Proje: Tren Bileti Satış ve Rezervasyon Sistemi")
print("🎓 Ders: Bilgisayar Mühendisliği - Veritabanı Yönetimi")
print()
print("👥 Proje Ekibi:")
print("   • Emirhan Gül - 221101073")
print("   • Onur Erçen - 231101035")
print("   • Nisa Eylül Çintiriz - 221101063")
print()
print("=" * 80)
print()

print("🏗️  MİMARİ:")
print("   İstemci (React) → Web Server (Flask API) → Veritabanı (MySQL)")
print()

print("🛠️  TEKNOLOJİ STACK:")
print("   • Veritabanı: MySQL 8.x")
print("   • Backend: Python 3.x + Flask")
print("   • Frontend: React 18 + Material-UI")
print("   • API: RESTful")
print()

print("=" * 80)
print("🚀 KURULUM ADIMLARI")
print("=" * 80)
print()

print("1️⃣  VERİTABANI KURULUMU:")
print("   cd database")
print("   mysql -u root -p < schema.sql")
print("   mysql -u root -p < seed_data.sql")
print()

print("2️⃣  BACKEND KURULUMU:")
print("   cd backend")
print("   python -m venv venv")
print("   .\\venv\\Scripts\\Activate.ps1")
print("   pip install -r requirements.txt")
print("   copy .env.example .env")
print("   # .env dosyasını düzenleyin")
print("   python app.py")
print()

print("3️⃣  FRONTEND KURULUMU:")
print("   cd frontend")
print("   npx create-react-app tren-rezervasyon-ui")
print("   cd tren-rezervasyon-ui")
print("   npm install axios react-router-dom @mui/material @emotion/react @emotion/styled")
print("   npm start")
print()

print("=" * 80)
print("📚 DÖKÜMANTASYON")
print("=" * 80)
print()
print("• Ana README: README.md")
print("• Backend Dokümantasyonu: backend/README.md")
print("• Frontend Dokümantasyonu: frontend/README.md")
print("• Ara Rapor: AraRAPOR1.txt")
print()

print("=" * 80)
print("🔗 ERİŞİM ADRESLERİ")
print("=" * 80)
print()
print("• Backend API: http://localhost:5000")
print("• Frontend UI: http://localhost:3000")
print("• API Health Check: http://localhost:5000/health")
print("• API Docs: http://localhost:5000/")
print()

print("=" * 80)
print("✨ ÖZELLİKLER")
print("=" * 80)
print()
print("Kullanıcı:")
print("  ✅ Sefer arama ve listeleme")
print("  ✅ Koltuk seçimi")
print("  ✅ Rezervasyon oluşturma")
print("  ✅ Ödeme (mock)")
print("  ✅ PNR ile bilet sorgulama")
print()
print("Yönetici:")
print("  ✅ İstasyon/Tren/Sefer yönetimi (CRUD)")
print("  ✅ Rezervasyon izleme")
print("  ✅ Doluluk oranı raporu")
print("  ✅ Gelir raporu")
print()

print("=" * 80)
print("📊 VERİTABANI YAPISI")
print("=" * 80)
print()
print("7 Ana Tablo:")
print("  1. İstasyon (istasyon_id, ad, sehir)")
print("  2. Tren (tren_id, kod, koltuk_sayisi)")
print("  3. Sefer (sefer_id, tren, istasyonlar, zamanlar)")
print("  4. Yolcu (yolcu_id, ad_soyad, eposta, telefon)")
print("  5. Rezervasyon (rezervasyon_id, pnr, tutar, durum)")
print("  6. Bilet (bilet_id, rezervasyon, sefer, yolcu, koltuk)")
print("  7. Ödeme (odeme_id, rezervasyon, yontem, tutar)")
print()
print("Özel Özellikler:")
print("  • Foreign Keys ve CASCADE/RESTRICT")
print("  • UNIQUE Constraints (eposta, pnr, sefer+koltuk)")
print("  • CHECK Constraints (fiyat > 0, zamanlar)")
print("  • Trigger'lar (kapasite kontrolü, tutar hesaplama)")
print("  • View'lar (sefer detayı, rezervasyon özeti)")
print("  • Index'ler (performans optimizasyonu)")
print()

print("=" * 80)
print("🎯 HIZLI TEST")
print("=" * 80)
print()
print("Backend test:")
print("  curl http://localhost:5000/health")
print()
print("Sefer listele:")
print("  curl http://localhost:5000/api/seferler")
print()
print("İstasyon listele:")
print("  curl http://localhost:5000/api/istasyonlar")
print()

print("=" * 80)
print()
print("💡 İpucu: Detaylı bilgi için README.md dosyasını okuyun!")
print()
print("🚀 Başarılar! İyi çalışmalar...")
print()
print("=" * 80)

# Kullanıcıdan input al
input("\nDevam etmek için Enter'a basın...")
